### ISSUE TITLE
MySQL Password Repeated In-Line

### ISSUE THREAD

**Issue by beittenc** [B33J/Batch#1]
https://github.com/B33J/Batch/blob/37a3c2489e93582b74b69ea54f98f54878373d23/copy%20WP%20site.bat#L130

There are several mysql commands in a row that have the password repeated. This requires multiple edits and, therefore, is prone to human error. It'd be best if this was included in a variable earlier in the file or some other central location.

**Comment by B33J** [comment]
This is indeed true if the password were to be changed.  A find&replace could be done to update that password to a variable, but the password never did change.  This script is also retired and will never be used again, so there's that.  :)
